# Generated by Django 4.0.5 on 2022-06-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='nick_name',
        ),
    ]
