# Generated by Django 4.0.5 on 2022-06-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=161)),
                ('last_name', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'user_informations',
            },
        ),
    ]
