# Generated by Django 4.0.5 on 2022-06-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_follow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
    ]
