# Generated by Django 4.0.5 on 2022-06-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_follow_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='nick_name',
            new_name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user'),
        ),
    ]
